# Generated by Django 3.0.4 on 2020-03-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200309_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
