# Generated by Django 3.0.4 on 2020-04-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200416_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
